name: Java Workflow Demo

on: [push]

jobs:
  Execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Java Version
        run: java -version
      - name: Identifying the Folder
        run: pwd
      - name: List the files in current directory
        run: ls ${{github.workspace}}
      - name: Run the Java File
        run: java helloworld
